### ISSUE TITLE
SlackチームにGotanda.pmな人を招待する

### ISSUE THREAD

**Issue by karupanerura** [gotanda-pm/gotanda-pm#21]
運営/交流用にSlackチームを作りました: https://gotanda-pm.slack.com/
メールアドレス書いて貰えれば招待します。（招待が終わったらコメントをowenrである僕が消します。）

**Comment by papix** [comment]
mail at papix.net です!!!!!!

**Comment by masasuzu** [comment]
m15.suzuki.masashi+gotandapm    at     gmail.com です

**Comment by myfinder** [comment]
ｺﾞﾀﾋﾟｰはいりたい
medianetworks at gmail.com です。

**Comment by kfly8** [comment]
++
kentafly88 at gmail.com

**Comment by karupanerura** [comment]
@papix @masasuzu @myfinder @kfly8 invited!

**Comment by key-amb** [comment]
@karupanerura 

昨日はありがとうございました！
yasutake.kiyoshi@gmail.com です！ 招待よろしくお願いしますmm

**Comment by karupanerura** [comment]
@key-amb こちらこそありがとうございました！invited!

**Comment by tokuhirom** [comment]
参加希望　tokuhirom@gmail.com

**Comment by uzulla** [comment]
参加したい！ zishida@himitsukichi.com

**Comment by m-fujisawa** [comment]
risou.f@gmail.com
よろしくお願いします。

**Comment by risou** [comment]
risou.f@gmail.com
よろしくお願いします。

**Comment by karupanerura** [comment]
@tokuhirom @uzulla @risou invited!

**Comment by zoncoen** [comment]
参加したいです！ zoncoen@gmail.com

**Comment by karupanerura** [comment]
@zoncoen invited!

**Comment by Songmu** [comment]
@karupanerura y.songmu@gmail.com

**Comment by karupanerura** [comment]
@Songmu invited!

**Comment by hiyoko9191** [comment]
hiyoko9191@gmail.com

**Comment by karupanerura** [comment]
@hiyoko9191 invited!

**Comment by trapple** [comment]
trapplejp@gmail.com お願いします！

**Comment by karupanerura** [comment]
@trapple invited!

**Comment by meru-akimbo** [comment]
merukatoruayu0@gmail.comで招待お願いします!

**Comment by karupanerura** [comment]
@meru-akimbo invited!

**Comment by shoichikaji** [comment]
@karupanerura skaji@outlook.com  inv お願いします！

**Comment by karupanerura** [comment]
@shoichikaji invited!

**Comment by myfinder** [comment]
MySQL Casualでも使ったのですが
https://github.com/rauchg/slackin
を使うと手間がかからず展開できていいのではないかと思いました。

**Comment by karupanerura** [comment]
なるほどよさげですね。立てます！

**Comment by karupanerura** [comment]
たてた
https://slackin-gotanda-pm.herokuapp.com/

**Comment by karupanerura** [comment]
こっちに書いたのでclose http://gotanda.pm.org/about.html

**Comment by bayashi** [comment]
https://slackin-gotanda-pm.herokuapp.com/ may not work.
Would you mind inviting me?

**Comment by karupanerura** [comment]
Thank you for your notice. I'll fix it.
I invited you to our slack team.

**Comment by bayashi** [comment]
Thank you!

**Comment by Likk** [comment]
perl@li.que.jp

**Comment by karupanerura** [comment]
@Likk invited!
