### ISSUE TITLE
新年会をやりたい

### ISSUE THREAD

**Issue by karupanerura** [gotanda-pm/gotanda-pm#26]
店候補:

* sakeおかわり（カジュアルに日本酒ぐいぐいいきたいよ派）
* わに家（酒にも料理にもこだわりたいよ派）
* あぶみ邸（酒もそこそこ料理もそこそこ良いのいきたいよ派）
* ぼたん（安くわいわいやりたいよ派）

ほか募集中

**Comment by silvers** [comment]
酒それ or 鳥それ

**Comment by masasuzu** [comment]
sakeおかわり

**Comment by masasuzu** [comment]
時期はいつあたりでしょうか? (気がつくと新年じゃないけど新年会になるおそれ

**Comment by karupanerura** [comment]
時期も含めて、希望を聞いている段階ですね。
特に希望がなければ25日週で適当に決めようかと。

**Comment by karupanerura** [comment]
やったぞ！
