### ISSUE TITLE
slackin-gotanda-pm 動くようにする

### ISSUE THREAD

**Issue by kfly8** [gotanda-pm/gotanda-pm#34]
https://slackin-gotanda-pm.herokuapp.com/

**Comment by kfly8** [comment]
[slackin](https://github.com/rauchg/slackin) が、
[now](https://zeit.co/now) をおすすめするように切り替わったようなので、
now で作ってみました

https://slackin-gotanda-pm.now.sh/

良さそうであれば、これに切り替えちゃいますー

**Comment by karupanerura** [comment]
神!!! めっちゃいいとおもいます！
既存のheroku側はこれ仕込んどきますね https://github.com/kenmickles/heroku-redirect

**Comment by kfly8** [comment]
ありがとうございます😊

**Comment by kfly8** [comment]
サイトのURLの変更done
あとは大丈夫そう!
